name: 改进建议
description: 为实验提出改进建议
title: "[建议] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你为改进实验提出建议！
        
        无论是关于任务设计、文档说明、测试用例，还是工具使用的想法，我们都很欢迎。你的反馈对实验的完善很有价值。
        
        如果你只是有个初步的想法，还没想清楚具体方案，也可以在[Discussions](discussions)中发起讨论，和大家一起探讨。

  - type: dropdown
    id: task
    attributes:
      label: 相关任务
      description: 这个建议主要涉及哪个任务？
      options:
        - 任务零：理解目标文件格式
        - 任务一：符号表查看器
        - 任务二：基础链接器
        - 任务三：多种地址引用方式
        - 任务四：符号冲突
        - 任务五：代码与数据分离
        - 任务六：内存保护机制
        - 任务七：静态链接库
        - Bonus 1：生成共享库
        - Bonus 2：链接使用共享库的程序
        - 实验文档
        - 测试框架
        - 工具链(cc/exec/readfle/disasm等)
        - C++指南
        - 整体设计
        - 其他
      multiple: true
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 描述当前实验中存在的问题或不足
      placeholder: 请详细说明你发现的问题
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: 改进建议
      description: 详细描述你的改进建议
      placeholder: 请具体说明你的改进想法
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: 预期效果
      description: 描述实施改进后会带来什么好处
      placeholder: 例如：提高学习效果、减少不必要的工作量等
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 实施建议
      description: 如果你有具体的实施方案，请在此说明
      placeholder: 可以包含具体的修改建议、新增内容等

  - type: textarea
    id: alternatives
    attributes:
      label: 其他方案
      description: 是否考虑过其他替代方案？为什么选择这个方案？
      placeholder: 请说明你考虑过的其他方案及其优缺点

  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      description: 在提交建议前，请确认以下内容
      options:
        - label: 我已经检查过现有的issues和discussions，确认这不是一个重复的建议
          required: true
        - label: 我已经清楚地说明了问题和改进方向
          required: true